version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: edfoewjiejfowfj    ## Hier Benutzer eingeben ##
      WORDPRESS_DB_PASSWORD: adkefkoewjfoififfeiuhf ## Hier Passwort eingeben ##
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.rule=Host(`entschleunigung-rollbarg.appen-etz.de`)"
      - "traefik.http.routers.wordpress.middlewares=default@file"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=http_resolver"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

    networks:
      - proxy
      - default
      - crowdsec

  wordpress-db:
    image: mariadb:10.6-focal
    container_name: wordpress-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: edfoewjiejfowfj     ## Hier selben Benutzer eingeben ##
      MYSQL_PASSWORD: adkefkoewjfoififfeiuhf   ## Hier selbes Passwort eingeben ##
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - default

networks:
  proxy:
    external: true
  crowdsec:
    external: true
