version: '3'

services:
  matomo-db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD= '1'
      - MYSQL_PASSWORD=abcdkfpskfprgorkgwpo           ## Hier Passwort eingeben ##
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
    networks:
      - default

  matomo-app:
    image: matomo:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=abcdkfpskfprgorkgwpo        ## Hier selbes Passwort eingeben ##
      - MATOMO_DATABASE_DBNAME=matomo
    networks:
      - default

  matomo-web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.rule=Host(`matomo.appen-etz.de`)"
      - "traefik.http.routers.matomo.tls=true"
      - "traefik.http.routers.matomo.tls.certresolver=http_resolver"
      - "traefik.http.routers.matomo.service=matomo"
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.matomo.middlewares=default@file"
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
